"""Original scenario cards that balance the expanded implementation library.
Run before build-curriculum.py. Questions and answers are hand-authored here.
"""
from pathlib import Path
import hashlib
import json

DECKS = [
("SQL · production queries", "Backend", "database", "blue", ["SQL", "PostgreSQL", "Transactions"], "PostgreSQL documentation", "https://www.postgresql.org/docs/current/", r'''
A join returns three copies of each order. What relationship should you investigate first?|Check whether the joined table has multiple matching rows per order. Joining a parent to its children multiplies the parent rows. Aggregate the children first or use EXISTS when you only need to test whether a match exists.
Why can a LEFT JOIN behave like an INNER JOIN after adding a WHERE condition on the right table?|Rows without a match contain NULL on the right. A condition such as WHERE payments.status = 'paid' rejects those rows. Put the condition in ON when you want to preserve unmatched left rows.
What does COUNT(column) exclude that COUNT(*) includes?|COUNT(column) ignores rows where that expression is NULL. COUNT(*) counts every row, including rows containing NULL values. Choose based on whether you are counting records or present values.
Why can NOT IN unexpectedly return no rows when its subquery contains NULL?|A comparison against NULL is unknown. NOT IN can therefore produce unknown rather than true, which WHERE excludes. Prefer a correlated NOT EXISTS or explicitly remove NULL from the subquery.
A paginated list skips or repeats rows during inserts. How does keyset pagination help?|Use a stable, unique ordering and request rows after the last observed key, such as WHERE (created_at, id) < (:time, :id) ORDER BY created_at DESC, id DESC. OFFSET positions shift as rows are inserted.
Why is ORDER BY created_at alone insufficient for reliable pagination?|Multiple records can have identical timestamps. Add a unique tie breaker, usually id, and include both columns in the cursor and ordering. Otherwise the database can return tied rows in different orders.
When can a composite index on (tenant_id, created_at) support a query well?|When the query filters by tenant_id and then filters or orders by created_at. The leading-column ordering matters. An index is not automatically useful for every query that mentions one of its columns; inspect the execution plan.
Why might an index make a write-heavy table slower?|Each insert, delete, and relevant update must maintain the index. Indexes also consume space and can increase write amplification. Keep indexes justified by important queries and measure their read benefits against write costs.
A query is slow only for one very large customer. What should you inspect?|Compare actual and estimated row counts in the execution plan for that customer's parameters. Skewed data, stale statistics, or a plan optimized for typical customers can cause poor join or scan choices.
What is the danger of running EXPLAIN ANALYZE on a production UPDATE?|It actually executes the statement. EXPLAIN without ANALYZE only plans it. If execution is necessary, use an appropriate safe environment or a carefully controlled transaction and understand effects that may not roll back.
Two requests read balance 100 and each writes balance 90. Why is one debit lost?|Both calculated from the same stale value. Use an atomic UPDATE balance = balance - 10, plus the necessary constraints or locking. Wrapping independent read-modify-write operations in a transaction alone does not guarantee correctness.
How can a database constraint protect a rule across every code path?|Define the invariant in the database, such as UNIQUE(tenant_id, external_id) or CHECK(quantity >= 0). The database enforces it even when another service, job, or migration writes data without your usual application validation.
Why should schema migrations often add a nullable column before requiring it?|Old application instances may still write rows without the new field. Add the column compatibly, deploy writers, backfill existing rows, verify completeness, then enforce the constraint. This supports rolling deployments.
What does SELECT ... FOR UPDATE achieve inside a transaction?|It locks selected rows against conflicting row modifications until the transaction ends. It is useful for coordinated updates, but can cause waiting and deadlocks. Keep transactions short and acquire locks in a consistent order.
How should an application respond to a serialization failure?|Retry the entire transaction using a bounded retry policy. Its reads and decisions may no longer be valid, so retrying only the final statement is insufficient. External side effects need separate idempotency protection.
Why is selecting every column a poor default for a hot API query?|It transfers and decodes unnecessary data, couples callers to schema changes, and may prevent efficient index-only access. Select the fields the response needs, while checking whether added joins cost more than the saved transfer.
'''),
("Distributed systems · failure scenarios", "Backend", "network", "violet", ["Reliability", "Queues", "Consistency"], "AWS Builders' Library", "https://aws.amazon.com/builders-library/", r'''
A worker commits a database update and crashes before acknowledging its message. What happens next?|The broker may redeliver the message. The worker must recognize an already completed operation, for example with a unique event ID recorded in the same transaction as the update. Acknowledgment timing alone cannot prevent every duplicate.
Why is writing to a database and then publishing an event a dual-write problem?|A crash between the two writes leaves inconsistent state. A transactional outbox records the business change and an outgoing event in one database transaction. A separate relay publishes the event and handles retries.
Does a transactional outbox eliminate duplicate events?|No. A relay can publish and crash before marking the outbox record sent. Consumers still need idempotent processing or deduplication. The outbox closes a lost-event gap between the database commit and event publication.
A service retries a failed request immediately five times. How can this worsen an outage?|Retries increase load on a dependency already failing. Use bounded retries with exponential backoff and jitter, a total deadline, and idempotency where needed. Avoid retrying independently at every layer of a call chain.
What is the difference between a timeout and a deadline across service calls?|A timeout bounds one operation. A deadline bounds the whole request. Propagate the remaining deadline so each downstream call cannot consume a fresh full timeout and make total latency grow without bound.
Why should a retry policy distinguish a connection failure from a validation error?|A transient transport failure may recover; invalid input will usually fail again. Retry only appropriate failure classes, respect the remaining deadline, and consider whether the operation might already have taken effect.
A cache entry expires on a popular key and thousands of requests hit the database. What is this called and how can you reduce it?|A cache stampede. Coalesce concurrent loads for the same key, refresh before expiry, add TTL jitter, or serve a bounded stale value while refreshing. The acceptable choice depends on freshness requirements.
Why can deleting a cache entry before committing a database update leave stale data cached?|Another request can miss the cache, read the old database value, and refill the cache before the transaction commits. Coordinate invalidation after commit and account for races, or use versioned entries and bounded freshness.
When is stale-while-revalidate a poor fit?|When serving stale data violates correctness, such as authorization revocation or a critical financial balance. It works better for data where bounded staleness is acceptable. Define the freshness contract before choosing the caching strategy.
How does a circuit breaker differ from a retry?|A retry attempts the operation again. A circuit breaker temporarily rejects calls after enough failures, giving the dependency time to recover. A half-open state permits limited probes before normal traffic resumes.
What does backpressure ask an overloaded producer to do?|Slow down, wait, or reject new work instead of allowing an unbounded queue to grow. Bound concurrency and queue capacity, and make overload behavior explicit so latency and memory usage remain controllable.
A distributed lock lease expires while a paused worker still runs. What prevents stale writes?|Use a fencing token that increases with each lock acquisition, and make the protected resource reject writes from older tokens. A lease alone cannot stop an old owner that resumes after a long pause.
Why can wall-clock timestamps be unsafe for ordering updates from different machines?|Clocks can be skewed or adjusted. Two writers may disagree about which update occurred later. Use an ordering mechanism appropriate to the problem, such as database versions, logical clocks, or a single authoritative sequencer.
What does eventual consistency promise, and what does it leave unspecified?|If writes stop and updates continue propagating successfully, replicas eventually converge. It does not by itself specify how long convergence takes, whether reads see your own writes, or how concurrent conflicts are resolved.
Why can a read replica show old data immediately after a successful write?|Replication may be asynchronous. For read-your-writes behavior, route the follow-up read to the primary, wait for a known replication position, or use a consistency mechanism supported by the datastore.
How can a poison message block useful work in a queue?|Repeated processing failures can monopolize retries or block an ordered partition. Use bounded attempts, useful failure diagnostics, and a dead-letter workflow. Preserve enough information to repair and replay the message safely.
'''),
("API design · contracts & edge cases", "Backend", "globe", "green", ["HTTP", "APIs", "Compatibility"], "MDN HTTP documentation", "https://developer.mozilla.org/en-US/docs/Web/HTTP", r'''
A client times out after creating an order. What should it send when retrying to avoid a duplicate order?|Reuse the same idempotency key for the same logical operation. The server should atomically associate the key with the operation result and reject incompatible payload reuse. Generating a new key for every retry defeats deduplication.
Should the server accept the same idempotency key with a different request body?|Usually no. Store a fingerprint of the relevant request and return a conflict when the same key is reused for a different operation. Document key scope, retention, and behavior while the original request is still running.
Why can returning HTTP 200 with an error-shaped body cause trouble?|Intermediaries, monitoring, and generic clients may treat it as success. Use an appropriate status code and a consistent machine-readable error body. Keep the error contract stable and include a request ID when useful.
When should an API return 202 Accepted instead of 201 Created?|Use 202 when work has been accepted but is not yet complete. Provide a way to check progress or receive completion. Use 201 when a resource has actually been created, often with its location.
What should a client do with a 429 response and Retry-After?|Respect the server's requested delay when practical, apply a bounded retry policy, and stay within the overall deadline. Retry-After can be a delay in seconds or an HTTP date, so parse both forms.
Why should API pagination cursors be treated as opaque by clients?|Their format is a server implementation detail and may change. Clients should pass cursors back unchanged. The server should validate cursor contents and bind them to relevant query constraints where necessary.
What makes adding a new enum value a potentially breaking API change?|Clients may use exhaustive switches, generated validators, or fixed dropdowns that reject unknown values. Design clients for forward compatibility or version the contract when a new value cannot be handled safely.
Why can removing a response field break clients even if it was undocumented?|Some clients may already depend on it. Observe usage where possible, communicate deprecation, provide a migration period, and test representative consumers. An undocumented behavior can still become a real dependency.
What is the purpose of an ETag in conditional updates?|It represents a resource version. A client can send If-Match with the version it edited; the server rejects an update if the resource changed. This prevents accidentally overwriting another writer's newer changes.
What should happen when If-Match does not match the current resource version?|The server normally returns 412 Precondition Failed. The client should fetch the current state and resolve the conflict, rather than silently retrying an overwrite with no precondition.
Why should a file upload enforce limits while streaming, not only after reading the entire body?|Otherwise a large request can exhaust memory or temporary storage before validation. Limit request size, stream with bounded buffers, validate content appropriately, and clean up partially written data on failure.
What is mass assignment in an API update endpoint?|Blindly copying client fields into a model can let clients change protected properties such as role or owner_id. Explicitly allow writable fields and apply authorization separately for the specific resource and operation.
Why should a webhook receiver verify the raw request body?|Signatures are usually computed over exact bytes. Parsing and reserializing JSON may change whitespace or ordering and invalidate the signature. Verify the documented signature scheme before trusting or processing the event.
How can an API handle long-running exports without holding a connection open?|Create an export job, return an accepted response with a job identifier, and expose status plus a result location when finished. Handle authorization, expiry, retry behavior, and cleanup for the exported data.
What is the difference between API authentication and object-level authorization?|Authentication establishes who is making the request. Object-level authorization checks whether that identity may act on this specific object. A valid login does not grant access to every record whose ID the caller can guess.
Why can automatically retrying POST requests be unsafe?|The first attempt may have committed even if the response was lost. Retry only when the operation is known to be safe or protected by an idempotency mechanism. The HTTP method name alone cannot tell you whether a specific endpoint deduplicates.
'''),
("Application security · practical defenses", "Backend", "globe", "amber", ["Security", "Authentication", "Web"], "OWASP Cheat Sheet Series", "https://cheatsheetseries.owasp.org/", r'''
Why do prepared statements prevent a typical SQL injection attack?|They keep SQL structure separate from data values, so input is not interpreted as SQL syntax. Dynamic identifiers such as table names still need explicit allowlists; parameter placeholders generally represent values, not arbitrary query structure.
Why is escaping HTML not sufficient when inserting data into JavaScript or a URL?|Escaping rules depend on the output context. A value safe in HTML text may be unsafe in a script, attribute, or URL. Use safe APIs and context-appropriate encoding, and avoid building executable code from untrusted strings.
An endpoint fetches a URL supplied by a user. What security boundary is at risk?|Server-side request forgery can make the server access internal services or metadata endpoints. Validate destinations and schemes, control redirects, and enforce network-level egress rules. String checks alone can be bypassed by alternate address forms or DNS changes.
Why is checking a filename for ../ an incomplete path traversal defense?|Paths can use encoding, platform-specific separators, or symlink resolution. Resolve the destination against an approved root and verify the final path remains inside it. Prefer server-generated storage names over arbitrary user paths.
What does HttpOnly protect a session cookie from?|It prevents ordinary page JavaScript from reading the cookie. It does not stop a script from making authenticated requests through the browser, so it is not a complete XSS defense. Use it alongside appropriate cookie and application protections.
Why is CORS not an authorization mechanism for your API?|CORS controls whether browser JavaScript can read cross-origin responses. Non-browser clients are not constrained by it, and some cross-origin requests can still be sent. Authenticate and authorize requests on the server.
When can a cookie-authenticated endpoint be vulnerable to CSRF?|A browser may automatically attach the user's cookie to an attacker-triggered request. Use appropriate SameSite settings, CSRF tokens or origin verification, and avoid state changes through safe methods such as GET.
Why should a password reset token be short-lived and single-use?|A captured token should offer only a small opportunity for abuse and become invalid after use. Generate it securely, store a safe representation, bind it to the intended account and action, and avoid leaking it through logs or referrers.
Why should password reset responses avoid revealing whether an email exists?|Different messages or timing can enable account enumeration. Return a consistent public response and apply rate limits while still sending a reset message only when appropriate. Keep detailed diagnostics in protected internal logs.
What should happen to existing sessions after a high-risk account recovery?|Consider revoking relevant sessions and refresh tokens, and notify the account owner. Recovery can mean credentials were compromised. The exact policy depends on risk and user experience, but should be explicit rather than accidental.
Why should access tokens be validated beyond simply decoding their payload?|Decoding proves nothing about authenticity. Verify the signature with an allowed algorithm and trusted key, then check relevant claims such as issuer, audience, expiry, and not-before. Reject tokens that do not satisfy the intended contract.
Why is a client-supplied role claim not sufficient for authorization?|The client can alter untrusted input. Use authenticated claims from a trusted issuer or look up authoritative permissions on the server. Even a verified role may need object ownership, tenant, and current policy checks.
What is a tenant isolation test for a multi-tenant API?|Create records under two tenants and verify that a user from one cannot read, modify, enumerate, or reference the other's records. Test direct IDs, nested resources, background jobs, and exports, not just the main listing endpoint.
Why should secrets be excluded from application logs?|Logs often have broader access, longer retention, and more downstream copies than primary data. Redact credentials and tokens before logging. If a secret is exposed, rotate it; deleting one log view may not remove every copy.
Why is Math.random unsuitable for generating authentication tokens?|It is not designed as a cryptographically secure random generator. Use a platform cryptographic random source with enough entropy and a suitable encoding. Unpredictability is essential because possession of the token often grants access.
What does defense in depth mean for an uploaded image?|Apply several independent controls: size limits, content validation, safe storage, controlled serving headers, and restricted processing. A filename extension alone does not establish file type or make a parser safe.
'''),
("TypeScript · model the invariants", "Foundations", "braces", "violet", ["TypeScript", "Types", "Validation"], "TypeScript handbook", "https://www.typescriptlang.org/docs/handbook/intro.html", r'''
Why is unknown a better type than any for an unvalidated JSON response?|unknown forces callers to narrow or validate before using the value. any disables useful checking and allows unsupported assumptions to spread. Static types do not validate data arriving at runtime.
What is unsafe about writing JSON.parse(text) as User?|A type assertion does not check the parsed value. Invalid data still reaches the program at runtime. Parse as unknown and validate the fields and invariants before treating the result as a User.
How does a discriminated union prevent impossible request states?|Give each variant a literal tag and only the fields valid for that state. For example, success carries data and failure carries an error. Narrowing on the tag makes the valid fields available without contradictory optional combinations.
How can never help check an exhaustive switch?|After handling every variant of a discriminated union, the remaining value should be never. Passing it to a function that accepts never makes the compiler report a missing case when a new variant is added.
Why can an optional property and a property explicitly containing undefined behave differently?|An absent property is not the same runtime object shape as a present property with value undefined. Object.keys, the in operator, serialization, and exactOptionalPropertyTypes can expose the distinction. Model the intended semantics.
What does readonly on an array prevent, and what does it not guarantee?|It prevents mutation through that typed reference. It does not necessarily freeze the runtime object or prevent mutation through another mutable alias. Use runtime controls or immutable data discipline when actual immutability matters.
Why does Object.freeze not automatically make a nested object deeply immutable?|It freezes only the object passed to it. Nested objects remain separate mutable objects unless frozen too. A readonly TypeScript type is also compile-time protection rather than a recursive runtime freeze.
When is a generic function more useful than one returning a union?|A generic can preserve relationships between inputs and outputs, such as returning the same element type supplied in an array. A broad union often loses that relationship and forces callers to narrow again.
What does keyof T represent?|The union of property key types known on T. It can constrain a key parameter so a generic accessor only accepts valid keys. The corresponding indexed access T[K] describes the value type for that key.
What does the satisfies operator help you check while preserving inference?|It checks that an expression is assignable to a target type while retaining the expression's inferred type information. This is useful for configuration objects where you want structural checking without broadly annotating every value.
Why can a non-null assertion hide a production bug?|The exclamation mark removes null and undefined from the static type without adding a runtime check. If the assumption is wrong, the program can fail later. Narrow explicitly or handle absence where it can actually occur.
Why is an array index read potentially undefined even when the element type is string?|The array might be empty or the index out of bounds. Enable and respect noUncheckedIndexedAccess where suitable, validate the index, or handle undefined instead of assuming every numeric key exists.
What makes a type predicate dangerous if implemented incorrectly?|The compiler trusts the predicate's promise. A function claiming value is User after only checking that value is an object can incorrectly narrow malformed data. Validate all required structure and relevant invariants.
Why are structural types not enough to distinguish a UserId from an OrderId when both are strings?|Both accept the same string values. Branded types can distinguish them statically after validated construction. The brand is a compile-time convention; runtime input still needs validation and correct association.
What is the difference between Partial<User> and a safe update command?|Partial<User> allows every User property to be optional, including fields that should never be writable. A dedicated update type should explicitly allow editable fields and represent operations such as clearing a value unambiguously.
Why should a library return Promise<Result> instead of hiding an asynchronous result behind a callback side effect?|The promise makes completion and errors composable through await and standard error handling. The exact API depends on whether there is one result or a stream, but callers should have an explicit contract for completion and failure.
'''),
("Testing · meaningful confidence", "Practice", "bug", "green", ["Testing", "Debugging", "Quality"], "Testing Library guiding principles", "https://testing-library.com/docs/guiding-principles/", r'''
Why is a test that mocks the function under test unable to verify its implementation?|It exercises the mock's behavior, not the real function. Mock external boundaries when necessary, then call the real unit and assert an observable outcome. A passing mock interaction alone may prove very little.
What is a useful invariant for a money transfer test?|The total balance should be conserved, exactly one debit and credit should occur, and failure should not leave a partial transfer. Test concurrency and duplicate requests where they are part of the real contract.
How can property-based testing complement a few hand-picked examples?|Generate many inputs and check general properties, such as decode(encode(x)) preserving x. It can find edge cases you did not anticipate, but the property must be meaningful and the generator must cover valid and boundary cases.
What is a metamorphic test when the exact output is hard to calculate?|Check a relationship between outputs after a controlled input transformation. For a sorting function, permuting the input should not change the sorted result. The relationship provides an oracle without hard-coding every answer.
Why is sleeping for two seconds a fragile way to test asynchronous UI behavior?|Machine load and scheduling vary. Wait for the expected observable condition with a bounded timeout instead. A fixed sleep can be both too slow when work is quick and too short when the environment is busy.
How should a flaky test investigation use failure evidence?|Capture the exact failure, seed, timing, environment, and relevant logs or traces. Identify uncontrolled time, shared state, races, or external dependencies. Repeating until green hides the symptom without establishing correctness.
What should a clock-dependent unit test control?|The current time, timezone assumptions, and any relevant timers. Pass a clock or explicit timestamp where possible. Include boundary cases such as midnight and expiry rather than relying on the machine's wall clock.
Why is a database integration test with only one row often misleading?|It does not expose duplicate joins, ordering ties, tenant leaks, NULL handling, or realistic selectivity. Use a small but deliberately varied fixture that exercises the query's important relationships and edge cases.
What is a contract test between two services intended to catch?|Disagreements about request and response formats, required fields, status codes, and behavior at the boundary. It complements unit and end-to-end tests; it does not prove the entire deployed workflow works.
What makes a regression test useful after fixing a bug?|It reproduces the triggering conditions and fails on the faulty behavior while passing on the corrected behavior. Assert the user-visible or domain outcome, rather than just the new helper's internal implementation.
Why can excessive snapshots make important regressions harder to see?|Large snapshots contain many incidental details, making updates routine and meaningful changes easy to miss. Prefer focused assertions for behavior and reserve snapshots for small, stable structures with reviewable differences.
How can you test idempotency beyond sending one successful request?|Repeat the same logical request, including concurrent attempts and a simulated lost response. Assert that only one side effect occurs and repeated callers get the documented result. Also test key reuse with a different payload.
Why is a test for an empty collection valuable even when normal examples pass?|Empty input often takes a different control path and exposes invalid reductions, missing defaults, and indexing assumptions. Decide the expected empty result explicitly instead of inheriting an accidental exception.
What does mutation testing reveal that line coverage does not?|It changes program behavior slightly and checks whether tests fail. Surviving meaningful mutations can reveal weak assertions. High line coverage only shows that code executed, not that incorrect outcomes would be detected.
How should an error-path test check transaction rollback?|Cause a failure after an intermediate write and verify that no partial state remains. Also verify that the caller receives the expected failure. Only asserting that an exception occurred can miss corrupted persisted state.
What should a mobile web test verify beyond the viewport width?|Touch target sizes, scrolling and overflow, keyboard behavior, focus visibility, safe areas, offline recovery, and persistence after navigation or reload. Exercise actual actions at a narrow viewport, not just a screenshot.
'''),
("Observability · diagnose production", "Practice", "bug", "amber", ["Observability", "SLOs", "Performance"], "Google SRE books", "https://sre.google/books/", r'''
Why can average latency look healthy while users report slow requests?|Averages hide tail behavior. Inspect latency percentiles, distributions, request classes, and errors. A small fraction of very slow requests can hurt users badly without moving the overall mean much.
What does p99 latency of 2 seconds mean?|Approximately 99 percent of observations in the measured population are at or below 2 seconds. It does not mean every user gets that latency or that the slowest request takes 2 seconds. The window and population matter.
Why should you not average p99 values from several servers to obtain a fleet p99?|Percentiles are not generally composable by averaging. Combine the underlying distributions or appropriate histogram data, then calculate the fleet percentile. Traffic volume and latency shape can differ across servers.
What is the difference between an SLI and an SLO?|An SLI is a measured indicator of service behavior, such as the fraction of successful requests. An SLO is the target for that indicator over a defined window. Define what counts as success and which traffic is included.
How does an error budget connect reliability to change decisions?|It represents the amount of unreliability allowed by an SLO. Rapid consumption can justify slowing risky changes and prioritizing reliability work. It is a decision tool tied to user-facing goals, not a generic uptime score.
Why is an alert on every single failed request usually noisy?|Some failures are expected or transient and may not threaten the service objective. Alert on actionable symptoms, sustained error rates, or error-budget burn, and provide enough context for an operator to decide what to do.
What makes a log's request ID useful during an incident?|It links events belonging to the same request across components. Propagate it consistently and include it in relevant logs. A trace ID can provide a broader causal view across distributed spans when tracing is available.
Why should user IDs be avoided as metric label values in a large service?|They create very high cardinality, which can overwhelm metric storage and queries. Keep metric dimensions bounded and use logs or traces for per-user investigation, with appropriate privacy controls.
A service's CPU is low but latency is high. What should you investigate?|Waiting on dependencies, database locks, connection pools, disk or network I/O, and queueing. CPU utilization alone cannot explain response time. Trace where time is spent before optimizing computation.
Why can increasing a connection pool make database latency worse?|More concurrent queries can exceed the database's useful capacity, increasing contention and queueing. Measure throughput and latency together, bound concurrency, and fix slow queries rather than assuming more connections always help.
What is saturation, and why can it precede visible errors?|A resource approaches its capacity, causing requests to queue. Latency often rises before requests time out or fail. Track relevant queues, pool utilization, CPU, memory, and other bottlenecks according to the system.
Why should deployment annotations appear on operational dashboards?|They help correlate behavior changes with releases or configuration updates. Correlation is a lead, not proof of causation; compare other evidence before deciding whether to roll back.
What should a useful incident timeline record?|Observed symptoms, user impact, meaningful state changes, actions taken, and their effects with timestamps. Separate observations from hypotheses so later analysis does not mistake an early guess for an established cause.
What makes a post-incident action item effective?|It has a concrete change, an owner, and a way to verify completion and impact. Prefer improvements to detection, prevention, or recovery over vague reminders to be more careful.
Why is profiling preferable to optimizing code that merely looks expensive?|A profile shows where representative workloads actually spend time or allocate memory. Intuition can focus effort on code that contributes little to total cost. Re-measure after the change to verify the intended improvement.
How can coordinated omission make a load test look better than reality?|A load generator that waits for a response before sending the next request reduces offered load when the service slows. This can hide queueing experienced under a steady arrival rate. Choose a workload model matching real traffic.
'''),
("Systems · processes & concurrency", "Foundations", "network", "blue", ["Operating systems", "Concurrency", "Linux"], "Linux man-pages project", "https://www.kernel.org/doc/man-pages/", r'''
What is the key memory isolation difference between processes and threads?|Processes normally have separate virtual address spaces. Threads in one process share its address space while keeping their own execution state and stacks. Shared memory makes communication convenient but requires coordination for mutable data.
Why can a race condition exist even if each individual read and write is atomic?|A larger read-modify-write sequence may not be atomic. Two workers can interleave between the steps and violate an invariant. Protect the whole critical operation with the appropriate synchronization or atomic primitive.
What four conditions are commonly required for a deadlock?|Mutual exclusion, holding resources while waiting, no forced resource preemption, and a circular wait. Breaking an applicable condition can prevent deadlock; for example, a consistent lock order prevents circular waiting.
How does a consistent lock acquisition order reduce deadlocks?|If every operation acquires locks in the same global order, operations cannot form a cycle by each holding one lock and waiting for an earlier one. The policy must cover all relevant code paths.
What is starvation in a concurrent system?|A task waits indefinitely or excessively because other tasks repeatedly receive the resources it needs. The system can keep making progress overall while that task does not. Fair scheduling or admission policies may help.
What is the difference between concurrency and parallelism?|Concurrency structures work so multiple tasks can make progress over overlapping time periods. Parallelism executes work simultaneously, usually on multiple cores or machines. An event loop can be concurrent without running JavaScript callbacks in parallel.
Why can a CPU-heavy callback freeze a browser even when it uses async syntax?|Async does not automatically move computation off the main thread. A long synchronous segment still blocks rendering and input. Split the work, reduce it, or move suitable computation to a worker.
What does a file descriptor represent on Unix-like systems?|It is a small integer handle for an open resource in a process, such as a file, socket, or pipe. Descriptors have lifecycle and limit constraints; leaking them can prevent the process from opening new resources.
Why should a server close sockets and files on both success and failure paths?|Resources can leak when exceptions or early returns bypass cleanup. Use structured cleanup such as finally blocks or language resource-management constructs. A leak may only appear after the process handles many requests.
What is virtual memory useful for beyond making memory look contiguous?|It provides address-space isolation and maps virtual addresses to physical memory or other backing. It supports protection and flexible allocation. It does not make memory unlimited; allocation and paging still have real costs and limits.
Why does swapping often hurt latency-sensitive services?|Accessing paged-out memory can require slow storage I/O, producing large and unpredictable delays. Observe memory pressure and working-set size, and configure deployment resources appropriately rather than treating swap as equivalent to RAM.
What is a context switch, and why can excessive switching hurt throughput?|The system saves one execution context and resumes another. Switching has overhead and can disrupt caches. Too many runnable threads can spend resources on scheduling rather than useful work, so concurrency should be measured and bounded.
Why can a blocking operation inside an event loop delay unrelated requests?|The loop cannot run other callbacks while blocked. Use non-blocking APIs where appropriate, offload blocking work, and monitor event-loop delay. A single slow synchronous operation can affect many concurrent connections.
What should graceful shutdown do before a server process exits?|Stop accepting new work, signal or drain in-flight work within a deadline, release resources, and exit with appropriate status. Coordinate with readiness and load balancing so new requests are not sent to a process that is shutting down.
Why should a process handle SIGTERM rather than assuming it will run forever?|Supervisors and deployment systems commonly use termination signals to request shutdown. Handling the signal allows bounded cleanup and draining. The process must still tolerate abrupt termination because cleanup is never guaranteed.
What does a bounded worker pool control?|The number of tasks executing concurrently. It prevents unlimited resource use, but an unbounded waiting queue can still exhaust memory. Bound both concurrency and queued work, with explicit behavior when capacity is reached.
'''),
("Delivery · containers & safe releases", "Practice", "git", "green", ["Docker", "CI/CD", "Deployment"], "Docker documentation", "https://docs.docker.com/", r'''
How does a container differ from a virtual machine at the operating-system boundary?|Containers typically isolate processes while sharing the host kernel. Virtual machines run guest operating systems on virtualized hardware. This affects isolation, compatibility, and resource overhead; containers are not a complete security boundary by default.
Why should a production container usually run as a non-root user?|It reduces the privileges available if the application is compromised or misbehaves. Also restrict capabilities, filesystem access, and mounted resources. Non-root execution is one control, not a guarantee of isolation.
What problem does a multi-stage container build solve?|It separates build tools and intermediate files from the runtime image. Copy only required artifacts into the final stage, reducing size and unnecessary components. Verify that runtime dependencies are still included.
Why should secrets not be baked into container image layers?|Images are copied, cached, and distributed, and earlier layers can retain files removed in later layers. Supply secrets through appropriate runtime or build-secret mechanisms. Rotate a secret if it has entered an image or repository history.
Why does pinning a base image improve reproducibility?|It makes the chosen image version explicit instead of silently changing with a mutable tag. A digest identifies exact content. Pinning also creates a responsibility to regularly update and rebuild for relevant fixes.
What is the difference between a readiness probe and a liveness probe?|Readiness asks whether an instance should receive traffic. Liveness asks whether it should be restarted. A dependency outage may make an instance unready without justifying restarts that add more load and disruption.
Why can an overly aggressive liveness probe cause an outage loop?|A slow or overloaded instance may be repeatedly restarted before it can recover, reducing capacity further. Set thresholds based on startup and runtime behavior, and distinguish a dead process from a temporarily busy one.
Why should database compatibility be considered before rolling back an application?|A new release may have changed stored data or schema in ways the old code cannot understand. Use compatible migration phases and test rollback assumptions. Reverting the binary does not automatically revert data changes.
What is a canary deployment intended to reveal?|It exposes a limited share of real traffic to a new version and compares meaningful health and business signals. It reduces initial blast radius, but needs a representative sample, clear thresholds, and a rollback path.
What makes a feature flag different from deploying a new binary?|A flag can control behavior independently of code deployment, enabling gradual rollout or rapid disablement. It adds configuration states and operational complexity, so give flags owners and remove obsolete ones.
Why should CI use a lockfile when installing dependencies?|It selects a reproducible dependency graph consistent with the project. Without it, fresh installations can resolve different versions. Reproducibility helps diagnose failures, but dependencies still need intentional updates and verification.
What should a build artifact contain to support traceability?|An association with the source revision, build inputs or dependency versions, and the build process that produced it. This helps reproduce, investigate, and roll back releases without guessing which code is running.
Why is building once and promoting the same artifact through environments useful?|It reduces differences caused by rebuilding separately for each environment. Keep environment-specific configuration separate where practical, and verify that the promoted artifact is the one tested.
What is the risk of running database migrations concurrently from every application replica?|Multiple instances can race, block each other, or apply non-idempotent operations twice. Coordinate migration execution through a dedicated step or an appropriate lock and record applied versions.
Why should a deployment have a time-bounded rollback decision?|Prolonged uncertainty can leave users exposed while the team debates whether symptoms are related. Define actionable success and failure signals in advance, then investigate with a clear path to restore service.
How can ephemeral application containers accidentally lose user data?|Files written only to the container's writable layer may disappear when it is replaced. Store durable data in an appropriate persistent service or volume, and test backup and restore rather than relying on a long-lived container.
'''),

]

result = []
for index, (name, track, icon, color, topics, label, url, raw) in enumerate(DECKS, 3001):
    cards = []
    for line in raw.strip().splitlines():
        front, back = line.split('|', 1)
        h = hashlib.sha256((name + front).encode()).hexdigest()
        card_id = f"d0000000-{h[:4]}-4{h[4:7]}-8{h[7:10]}-{h[10:22]}"
        cards.append({"id": card_id, "front": front, "back": back, "kind": "scenario"})
    assert len(cards) == 16, (name, len(cards))
    result.append({"id": f"a0000000-0000-4000-8000-{index:012}", "name": name, "track": track, "icon": icon,
                   "color": color, "topics": topics, "description": "Reason through realistic engineering decisions and failure cases.",
                   "resource": {"label": label, "url": url}, "cards": cards})
destination = Path(__file__).resolve().parents[1] / 'src/data/authored-expansion.json'
destination.write_text(json.dumps(result, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print(f"Wrote {sum(len(deck['cards']) for deck in result)} original cards across {len(result)} decks.")
