"""Original, beginner-friendly lessons about building and debugging CRUD apps.

Imported by the beginner and follow-on authors. Keys are permanent card identities.
"""


def lesson(key, title, question, plain, example, analogy, mistake, check, answer):
    return dict(key=key, title=title, aliases=[], question=question, plain=plain,
                example=example, analogy=analogy, mistake=mistake, check=check, answer=answer)


GUARD = lesson(
    'crud-guard', 'Reject bad input before doing work',
    'A save function receives a blank task title. Where should you handle that?',
    'Check the input before saving anything. A guard clause is an early return for a case that cannot continue. It keeps the normal save path easy to read and prevents an invalid value from reaching the write operation. The server must also validate requests because a browser check can be bypassed.',
    '```js\nfunction validateTitle(title) {\n  if (typeof title !== "string") return "Enter a title";\n  if (!title.trim()) return "Enter a title";\n  return null;\n}\n```\n\nA message means validation failed; null means this check passed. The caller displays the message and stops before saving.',
    'A receptionist checks that a form has a name before passing it to the filing desk. An incomplete form goes back for correction immediately.',
    'Do not show an error and then keep executing the save. Reporting an error and stopping the operation are separate steps. Do not assume this one check validates every field.',
    'A handler displays "Title required" but still calls saveTask afterward. What is missing?',
    'Stop that path with an early return, or put the save in the valid-input branch. Showing a message alone does not stop the rest of the handler from running.')

BEGINNER = [
    lesson('crud-meaning', 'Turn a screen into four data operations',
           'In a task tracker, what do the four letters in CRUD mean?',
           'Create adds a task, Read loads tasks, Update changes a task, and Delete removes a task. These are operations on stored records. A screen can combine several operations: an edit page first reads a task and later submits an update. Start by connecting each user action to the data it needs to read or change.',
           'For a notes app: clicking New creates a note; opening the list reads notes; changing a title updates one note; confirming removal deletes it. A search box changes which records the Read operation returns.',
           'A filing cabinet lets you add a folder, open it, replace a page, or remove the folder. The web page is the handle you use; the stored records are the folders.',
           'Changing what is visible on a page does not necessarily change stored data. A note added only to a local array can disappear when the page reloads.',
           'A user marks a saved task as completed. Which CRUD operation is this?',
           '**Update.** The existing task keeps its identity while its completed field changes. Creating a second task would leave two records instead of updating the original.'),
    lesson('crud-save-path', 'Follow a save from button to database',
           'What should happen between clicking Save on a form and showing "Saved"?',
           'The browser gathers the input and sends a request. The server checks the caller, validates the allowed fields, and writes the change to storage. It returns a result that the browser handles. Show a success message after the response confirms the operation succeeded, and show a useful error if it fails.',
           'A title edit sends PATCH /tasks/42 with a new title. The server checks access to task 42, validates the title, saves it, and returns the saved task. The screen uses that returned value so server normalization appears immediately.',
           'Handing a letter to a courier is different from receiving proof of delivery. Starting a request is the handoff; a successful response is the confirmation defined by your API.',
           'A resolved fetch promise does not automatically mean a successful HTTP status. Check response.ok or the status before treating the response as a successful save.',
           'A Save request returns HTTP 400. Should the form clear its fields and show success?',
           '**No.** Keep the entered values and explain the validation problem. Let the user correct the form and retry without retyping everything.'),
    lesson('crud-record-id', 'Use the record ID when editing or deleting',
           'Why should an edit button use a task ID instead of its position in the list?',
           'An ID identifies the stored task. A list position only describes where it happens to appear right now. Sorting, filtering, and paging can all change that position. Keep the ID with the displayed record and send it with updates and deletions so the server targets the intended record.',
           'The first visible row is task 42 today. After sorting by title, the first row may be task 19. An Edit link to /tasks/42 still means task 42; a request that means "edit row zero" can point at the wrong task.',
           'A customer number identifies a person even when the waiting room order changes. A seat number identifies a location in the room, not a lasting identity.',
           'A record ID is not permission to access it. The server must still check that the current user can read or change the requested record.',
           'After filtering a task table, deleting row index 0 removes a different task. What should the request identify?',
           'Send the displayed task\'s stable ID. Resolve that ID on the server within the current user\'s allowed records, then perform the deletion.'),
    lesson('crud-form-state', 'Keep unfinished edits separate from saved data',
           'Why keep form draft values separate from the saved record?',
           'A draft is what the user is currently typing. The saved record is what the server has accepted. Keeping them separate makes Cancel meaningful and lets failed saves leave the original record intact. Copy the fields you edit into form state, and replace the saved view only when the save succeeds.',
           'The stored title is "Shopping". The user types "Weekend shopping" into a draft input. Cancel discards the draft. Save submits it and updates the displayed record after confirmation.',
           'Write proposed changes on a sticky note before replacing the official page. Throwing away the sticky note should not change the official page.',
           'Do not mutate a shared record object while typing. Another component may display those unsaved changes as if they were already stored. Nested edited objects also need independent copies.',
           'Cancel closes an edit dialog, but the task list still shows the unsaved title. What likely happened?',
           'The form changed the same object used by the list. Store editable draft fields separately and discard that draft on Cancel instead of mutating the saved record.'),
    lesson('crud-screen-states', 'Distinguish loading, empty, and failed lists',
           'A task list has no rows yet. Why is "No tasks" not always the right message?',
           'There are different reasons a list has no visible rows. The request may still be loading, it may have failed, or it may have succeeded with zero results. Keep those states explicit. Show an empty-state invitation only after a successful response confirms there are no matching records.',
           'While GET /tasks runs, show a loading indicator. On a network error, show Retry. On a successful empty array, show "No tasks yet" and an Add task button. A filtered empty result can instead suggest clearing the filter.',
           'An empty mailbox, a delivery still on its way, and a broken mailbox lock all look like "no letter in my hand," but each situation needs a different response.',
           'Do not turn every caught error into an empty array. That hides failures and tells the user their records are gone when the app simply could not load them.',
           'GET /tasks fails because the phone loses signal. What should the list show?',
           'Show a connection error and a retry action. If previously loaded data is visible, explain that it may be stale; do not present the failure as a successful empty list.'),
    lesson('crud-required-field', 'Validate on both sides of the request',
           'If an HTML input is required, why must the API also reject a blank title?',
           'Browser validation gives quick feedback during normal form use. The API can receive requests from other clients or a modified browser, so it must enforce its own rules. Check types, trim where appropriate, and validate required values at the server boundary before changing the database.',
           'A title consisting of three spaces may satisfy a simple nonempty check. For an API whose rule is a nonblank title, require a string, trim it, then reject the result if it is empty. Apply the agreed maximum length too.',
           'A reminder on the outside of a form helps people fill it out. The clerk still checks the actual submitted form before accepting it into the records.',
           'Do not trust a TypeScript type or a hidden browser field to validate an incoming request. Types guide your code, while runtime checks handle the values actually received.',
           'A client sends title: null even though your form only sends strings. What should the API do?',
           'Reject it with the API\'s validation response. Check the value\'s type before calling string methods, and do not turn the invalid value into an accidental stored title.'),
    lesson('crud-delete-flow', 'Make deletion clear and recoverable when needed',
           'What should a delete confirmation tell the user in a CRUD app?',
           'Name the record being removed and describe the effect. If deletion also removes related records, say so. Give the user a clear way to cancel. After confirmation, handle the server response before treating removal as final, and keep an error or recovery path if the operation fails.',
           'A project confirmation could say "Delete Website redesign and its 8 tasks?" The server performs the allowed operation. If it returns a failure, keep the project visible and explain that deletion did not complete.',
           'A labeled shredder tray lets you see which document you are about to destroy. A button labeled only "Are you sure?" gives much less help in catching a mistake.',
           'Confirmation is a usability step, not an access check. The server still needs permission checks and an explicit rule for related rows, even when the user clicked Confirm.',
           'The UI removes a task immediately, but DELETE returns a server error. What must an optimistic UI do?',
           'Restore the task or refresh authoritative data, and show the failure. An optimistic change is provisional; leaving the task hidden would misrepresent what was stored.'),
    lesson('crud-list-filter', 'Keep list filters in the request',
           'Why can filtering only the current page give misleading search results?',
           'The browser may have loaded only a small slice of the records. Filtering that slice cannot find matches on other pages. If search is meant to cover all accessible tasks, send the filter to the server and let it apply the filter before paging the result.',
           'You loaded page 1 with 20 tasks, but a matching task is on page 4. Sending GET /tasks?search=invoice&page=1 lets the server search the full allowed collection. Filtering the first 20 locally would incorrectly show no match.',
           'Looking for a book on the first shelf is not the same as searching the library catalog. You need the catalog when the search promises to cover the whole library.',
           'Reset the page or cursor when filters change. Page 8 of an unfiltered list may not exist once the result is narrowed to a handful of matches.',
           'A user changes a task filter while viewing page 5 and gets an empty page despite matching records. What should you check?',
           'Reset pagination for the new filter and request its first page. Also check that the API applies the filter before limiting the rows returned.'),
]

PRACTICAL = [
    lesson('next-crud-double-submit', 'Handle a double click on Create',
           'A slow Create task request gets clicked twice and produces two tasks. How do you fix the whole flow?',
           'Disable the submit action while that form request is pending to prevent accidental clicks. Also consider retries and other clients: for operations that must create only once per logical attempt, use a server-supported idempotency key. The server coordinates that key with the stored result so repeated attempts can return the original result.',
           'The form creates one request key when a new save attempt starts and reuses it if that same attempt is retried after a timeout. A later, deliberately new task gets a new key. The server enforces uniqueness and rejects reuse with different input.',
           'A claim ticket identifies one order. Presenting the same ticket twice should retrieve the same order, while a new order needs a new ticket.',
           'A disabled button protects only this open form. It does not protect against a retry after a lost response, another tab, or two requests arriving at the server together.',
           'After a timed-out create, the client generates a fresh idempotency key for the retry. What goes wrong?',
           'The server sees a new attempt and may create another record. Reuse the same key and payload when retrying that logical operation, according to the API contract.'),
    lesson('next-crud-conflict', 'Avoid silently overwriting another editor',
           'Two people edit the same customer record. How can the second save avoid overwriting the first?',
           'Include a version from the record the form loaded. The server updates only if the stored version still matches. If another save has changed it, report a conflict and let the user reload or reconcile their edits. The version check and write must be one coordinated database operation.',
           'An update can use WHERE id = :id AND version = :oldVersion and set version = version + 1. If no allowed row matches, the server determines whether the record changed or no longer exists. The form keeps its draft while showing the conflict.',
           'A checkout slip records which edition you borrowed. You cannot silently replace the current edition with handwritten changes based on an older one.',
           'Checking the version in one request and updating unconditionally afterward leaves a race between the two steps. Put the condition in the write or use your database\'s concurrency mechanism.',
           'An edit form loaded version 7, but the server now has version 8. Should it automatically overwrite version 8?',
           '**No.** Show a conflict and help the user compare or reload. Blindly retrying the stale draft removes the protection and can discard the other person\'s changes.'),
    lesson('next-crud-duplicate-email', 'Enforce uniqueness where records are stored',
           'Two registration requests both check that an email is unused, then both insert it. What prevents duplicates?',
           'A pre-check can improve feedback, but it cannot guarantee uniqueness while requests overlap. Define the intended uniqueness rule and enforce it with a database constraint or unique index. Catch the constraint failure and translate it into an appropriate, understandable application response.',
           'If the application uses a normalized email field as its account identifier, enforce uniqueness on that stored identifier. Both requests may pass an earlier availability check, but the database admits only one conflicting value.',
           'Two clerks can both see an empty seat on an old printout. A central reservation system must decide who actually gets the seat at the moment of booking.',
           'Be explicit about normalization and scope. Unique within one organization differs from unique across the entire application. Do not assume every email comparison rule is interchangeable.',
           'Can a "Check availability" endpoint replace a database uniqueness rule?',
           '**No.** Another request can claim the value after the check. Treat the check as feedback and the database constraint as the final enforcement at write time.'),
    lesson('next-crud-stale-search', 'Stop an old search response replacing a new one',
           'A user types "cat", then "caterer", but the screen ends up showing results for "cat". Why?',
           'Requests can finish in a different order from the order they started. The earlier search may be slower and arrive last. Associate results with the active query or request generation and apply only the current result. Cancel obsolete requests where supported to avoid unnecessary work.',
           'Request A searches cat. Request B searches caterer and finishes first. If B is the current request, ignore A when it eventually finishes. Loading and error state should also belong to the active request, so A cannot clear B\'s spinner or replace B\'s error.',
           'You ask two assistants for different reports. The report delivered last is not necessarily the report you requested most recently.',
           'Debouncing reduces how often requests start; it does not guarantee their completion order. An old in-flight request can still finish after the latest one.',
           'Does waiting 300 milliseconds before issuing each search fully prevent stale results?',
           '**No.** It reduces request volume but does not order responses. Use cancellation and/or a current-request check before updating results, errors, and loading state.'),
    lesson('next-crud-mass-assignment', 'Choose which fields an update may change',
           'Why is saving every property from a profile request into the user row dangerous?',
           'An incoming object can contain fields that the form never offered. Build an update command from explicitly allowed fields and validate each one. Sensitive fields such as owner IDs, account roles, and approval status must come from trusted logic or separate authorized operations.',
           'A profile edit accepts displayName and bio. Construct an update containing only those fields. If the body also contains isAdmin: true, that value must not become part of the database update.',
           'A change-of-address form authorizes changing an address. Writing "make me the manager" in the margin should not grant the clerk authority to change your job title.',
           'Hiding a field in the interface is not a defense: callers can construct JSON directly. Likewise, a broad Partial<User> type is not a runtime allowlist.',
           'The browser sends ownerId along with a new note. Which value should determine ownership?',
           'Derive ownership from the authenticated server context or an explicitly authorized sharing workflow. Do not let an arbitrary request body choose whose data the note belongs to.'),
    lesson('next-crud-child-rows', 'Delete a parent without leaving broken references',
           'What must you decide before allowing deletion of a project that still has tasks?',
           'Choose a product rule for dependent records. You might block deletion until tasks are moved, delete the tasks too, or retain an archived parent. Enforce the chosen rule with the database relationship and application behavior, and explain the effect before the user confirms.',
           'If deleting a project should delete its tasks, a suitable foreign-key cascade can enforce that relationship. If tasks must survive, prevent the deletion or move them through an allowed workflow. Related changes that must succeed together belong in one transaction.',
           'Removing a binder also affects the pages inside it. Decide whether the pages are destroyed, moved, or kept with an archived binder before taking it off the shelf.',
           'Deleting the parent in one request and children in later requests can leave a partial result. Do not add a cascade without checking which records it will remove.',
           'A project DELETE fails with a foreign-key violation. What should you investigate first?',
           'Inspect which child rows reference that project and the relationship\'s delete rule. Then implement the intended product behavior instead of disabling the constraint to force the deletion.'),
    lesson('next-crud-null-patch', 'Distinguish leaving a field alone from clearing it',
           'In a partial profile update, how can an omitted phone field differ from phone: null?',
           'A partial-update contract can define omission as leaving a value unchanged and explicit null as clearing it. The server must preserve that distinction when validating and building its update. An empty string is a third input whose meaning should also be defined rather than guessed.',
           'Stored phone is "555-0100". A body containing only displayName keeps that phone. A body containing phone: null clears it if the field is nullable and the API allows clearing it.',
           'Leaving an instruction box blank can mean "do nothing to this field." Writing "erase this value" is a separate instruction with a different result.',
           'Using incoming.phone ?? existing.phone treats null like omission and prevents clearing. Conversely, filling every missing property with null can erase values the user never intended to change.',
           'A PATCH request changes only a biography, but the server clears the address too. What may be wrong?',
           'The server likely converted omitted fields into empty or null values. Apply only supplied, permitted fields and handle explicit clearing according to the update contract.'),
    lesson('next-crud-list-refresh', 'Refresh the views affected by a successful save',
           'The API saved a task successfully, but the task list still shows the old title. What should you check?',
           'The screen may be showing a cached copy that was never updated or invalidated. Decide which views depend on the changed record. Use the saved response to update those copies, or mark the relevant queries stale and fetch them again. Include filters and sort order when deciding where the record belongs.',
           'A task changes from open to completed. Remove it from an open-only list or refetch that list after success. Also update its detail view and counts if they are displayed. Replacing just the title in one unrelated list is not enough.',
           'Changing the master address book does not automatically update every printed contact sheet. Each copy needs to be replaced or refreshed.',
           'Do not indiscriminately clear all application data after every save. Target the records and queries affected by the mutation, and handle refetch failures without claiming the save failed.',
           'A completed task still appears under the "Open" filter after a successful save. Is changing its checkbox enough?',
           'No. Membership in the filtered list changed too. Update the list consistently or refetch it using the active filter, and refresh any affected totals.'),
    lesson('next-crud-safe-sort', 'Allow users to sort without accepting SQL syntax',
           'A table accepts sort=title from the URL. How should the API use it in a database query?',
           'Map public sort options to a small set of trusted query expressions. Bind ordinary filter values using the database driver. A parameter placeholder usually represents a value, so it does not automatically make arbitrary table names, column names, or sort directions safe.',
           'Accept title and newest as named choices. Map title to a fixed title ordering with ID as a tie breaker, and newest to a fixed created-at ordering with ID as a tie breaker. Reject or default unknown choices according to the API contract.',
           'A restaurant lets you choose from a menu. It does not let the text you write in the order box become instructions for rewiring the kitchen.',
           'Do not append a raw sort string to SQL. Also specify a stable tie breaker so records with equal titles do not jump unpredictably between pages.',
           'Does putting a user-provided column name in a value parameter select that SQL column?',
           'Usually no: parameters bind data values, not arbitrary SQL identifiers. Choose the column through an allowlist or a safe query-builder API that enforces the allowed options.'),
    lesson('next-crud-test-feature', 'Test a feature through its stored result',
           'What would a useful end-to-end test for editing a task verify?',
           'Start from a known task, open its edit form, change an allowed value, and save. Verify the displayed result and reload to confirm the change was persisted. Add focused failure coverage for invalid input and access rules, rather than treating a visible success toast as proof of correctness.',
           'Create a task named Draft. Edit it to Ready, wait for the save response, and reload the page. Ready should still appear on the same task ID. In a separate API test, a different user should not be able to edit that task.',
           'Testing a light switch means checking that the lamp lights up, not just that the switch makes a clicking sound. A toast is a signal; the persisted behavior is the outcome.',
           'A test that mocks every write and checks only for "Saved" can pass while the database update is broken. Keep component tests for UI details and at least one integrated check for persistence.',
           'An edit test passes until it reloads the page, then the old title returns. What does that reveal?',
           'The visible update was not successfully persisted or reloaded from the expected storage. Trace the request, response, database write, and subsequent read instead of only adjusting the toast.'),
]
