import type { StarterCard } from "./curriculum";
import manifest from "./section-expansion-manifest.json";

interface ExpansionPack { id: string; cards: StarterCard[] }

// The manifest is generated by scripts/build-reviewed-content.mjs together with the packs it lists.
export const sectionExpansionVersion: number = manifest.version;
const additions = new Map<string, number>(
  manifest.sections.map((section) => [section.id, section.added]),
);
export const sectionAdditionCount = (deckId: string): number => additions.get(deckId) ?? 0;

// Packs load only during installation; they are never part of the application shell.
// Archived retrieval-*.json fixtures stay out of the glob: they exist for migration audits.
const chunks = import.meta.glob<string>("./section-packs/reviewed-*.json", {
  query: "?raw", import: "default",
});
let loading: Promise<ExpansionPack[]> | undefined;
export function loadSectionExpansion(): Promise<ExpansionPack[]> {
  loading ??= Promise.all(manifest.chunks.map(async (name) => {
    const load = chunks[`./section-packs/${name}`];
    if (!load) throw new Error(`Missing curriculum chunk: ${name}`);
    return JSON.parse(await load()) as ExpansionPack[];
  })).then((packs) => packs.flat()).catch((error) => {
    loading = undefined;
    throw error;
  });
  return loading;
}
